src/Entity/Comment.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use JetBrains\PhpStorm\Pure;

/**
 * @ORM\Table(name="comment")
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    private const PUBLISHED = true;
    private const DRAFT = false;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="text")
     */
    private string $text;

    /**
     * @ORM\ManyToOne(targetEntity=Review::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $review;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $user;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private \DateTimeImmutable $create_at;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private \DateTimeImmutable $update_at;

//    /**
//     * @ORM\Column(type="boolean")
//     */
//    private bool $is_published;

    public function __construct()
    {
        $this->create_at = new \DateTimeImmutable();
        $this->update_at = new \DateTimeImmutable();
    }

    #[Pure] public static function create(string $text, User $user, Review $review): Comment
    {
        $comment = new self();
        $comment->text = $text;
        $comment->review = $review;
        $comment->user = $user;

        return $comment;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getText(): string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getReview()
    {
        return $this->review;
    }

    public function setReview($review): self
    {
        $this->review = $review;

        return $this;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser($user)
    {
        $this->user = $user;
    }

    public function getCreateAt(): \DateTimeImmutable
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeImmutable $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getUpdateAt(): \DateTimeImmutable
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeImmutable $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    public function getIsPublished(): bool
    {
        return $this->is_published;
    }

    public function setIsPublished(): self
    {
        $this->is_published = self::PUBLISHED;

        return $this;
    }

    public function setIsDraft(): self{
        $this->is_published = self::DRAFT;

        return $this;
    }
}

src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private string $email;

    /**
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string", nullable=false)
     */
    private string $password;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="user", orphanRemoval=true)
     */
    private $review;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="user")
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $username;

    public function __construct()
    {
//        $this->review = new ArrayCollection();
//        $this->comments = new ArrayCollection();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): ?string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getReview(): ?Review
    {
        return $this->review;
    }

    public function setReview(Review $review): self
    {
        // set the owning side of the relation if necessary
        if ($review->getUserId() !== $this) {
            $review->setUserId($this);
        }

        $this->review = $review;

        return $this;
    }

    /**
     * @return Collection
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->review->contains($review)) {
            $this->review[] = $review;
            $review->setUser($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getUser() === $this) {
                $review->setUser(null);
            }
        }

        return $this;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }
}

src/Form/CommentType.php
<?php

namespace App\Form;

use App\Entity\Comment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('text', TextareaType::class, [
                'label' => 'new comment: ',
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Save',
                'attr' => [
                    'class' => 'form-control btn-block btn-success'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Comment::class,
        ]);
    }
}

src/Controller/CommentController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Review;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/{_locale}/user/comment', requirements: ["_locale" => "en|ru"])]
class CommentController extends AbstractController
{
    public function __construct(
        private EntityManagerInterface $em,
        private CommentRepository $commentRepository,
    ) {
    }

    #[Route('/', name: 'comment_index', methods: ['GET'])]
    public function index(): Response
    {
        $comments = $this->commentRepository->findBy(['user' => $this->getUser()], ['create_at' => 'DESC'],);
        return $this->render('user/comment/index.html.twig', [
            'comments' => $comments,
        ]);
    }

    #[Route('/new/{id}', name: 'comment_new', methods: ['GET', 'POST'])]
    public function new(Request $request, Review $review): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment, [
            'action' => $this->generateUrl('comment_new', [
                'id' => $review->getId()
            ]),
            'method' => 'POST',
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment = $form->getData();
            $comment
                ->setReview($review)
                ->setUser($this->getUser())
            ;
            $this->em->persist($comment);
            $this->em->flush();

            return $this->redirectToRoute('review', [ 'id' => $review->getId(),], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('user/comment/_form.html.twig', [
            'form' => $form,
            'comment' => $comment,
            'review' => $review,
        ]);
    }

    #[Route('/{id}/edit', name: 'comment_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Comment $comment,): Response
    {
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->flush();

            return $this->redirectToRoute('comment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/comment/edit.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/delete/{id}', name: 'comment_delete', methods: ['GET','POST'])]
    public function delete($id): Response
    {
        $comment = $this->commentRepository->find($id);
        $this->em->remove($comment);
        $this->em->flush();

        return $this->redirectToRoute('comment_index', [
            'comment' => $comment,
        ]);
    }
}

src/Controller/UserController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Review;
use App\Entity\User;
use App\Repository\ReviewRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/{_locale}/user', requirements: ["_locale" => "en|ru"])]
class UserController extends AbstractController
{
    public function __construct(
        private ReviewRepository $reviewRepository,
    ) {
    }

    #[Route('/', name: 'user')]

    public function index(): Response
    {
        return $this->render('user/index.html.twig',);

    }

    #[Route('/reviews', name: 'user_reviews')]

    public function showReviews(): Response
    {
        $reviews = $this->reviewRepository->createQueryBuilder('r')
            ->where('r.user = :user_id')
            ->setParameter('user_id', $this->getUser())
            ->orderBy('r.create_at', 'DESC')
            ->getQuery()
            ->getResult()
        ;
        return $this->render('user/review/user_reviews.html.twig', [
            'reviews' => $reviews,
        ]);
    }

    #[Route('/review/{id}', name: 'show_user_review')]
    public function showUserReview($id): Response
    {
        $review = $this->reviewRepository->find($id);
        return $this->render('user/review/show_user_review.html.twig', [
            'review' => $review,
        ]);
    }
}

templates/user/comment/_form.html.twig
{#{% extends 'base.html.twig' %}#}

{#{% block title %} Create new comment{% endblock %}#}

{% block body %}
{#    <a href="{{ path('review', {'id': review.id }) }}"><<< back to review</a>#}

    {{ form_errors(form) }}
    {{ form(form) }}


{% endblock %}

templates/user/comment/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %} {{ 'user.comment.edit.title' | trans}} {% endblock %}
{% block body %}
    <a href="{{ path('comment_index') }}"><<< {{ 'user.comment.edit.back.to.list' | trans }}</a><hr><br><br>
    {{ form_errors(form) }}
    {{ form(form) }}
    <a href="{{ path('comment_delete', { id: comment.id }) }}" class="btn btn-block btn-danger">{{ 'user.comment.edit.delete' | trans }}</a>

{% endblock %}

templates/user/comment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'user.comment.index.title' | trans }}{% endblock %}

{% block body %}
    <h1 CLASS="text-center">{{ 'user.comment.index.header' | trans }}</h1><br><hr><hr>

        {% for comment in comments %}
            <p>
                <small>{{ 'user.comment.index.comment.for.review' | trans }}: </small><a href="{{ path('review', {'id': comment.review.id}) }}">{{ comment.review.title}}</a> <small>{{ 'user.comment.index.from.author' | trans }}: </small> {{ comment.review.user.username }}
            <p>
                <small>
                    {{ 'user.comment.index.date' | trans }}: {{ comment.createAt |format_datetime('medium', 'short') }}
                </small>
            </p>

            <p>{{ comment.text}}</p>
            <a href="{{ path('comment_edit', { id: comment.id }) }}" class="btn btn-warning">{{ 'user.comment.index.edit' | trans }}</a>
            </p><hr><hr><br>
        {% else %}
            <tr>
                <td colspan="6">{{ 'user.comment.index.no.records.found' | trans}}</td>
            </tr>
        {% endfor %}


{#    <a href="{{ path('comment_new') }}">Create new</a>#}
{% endblock %}

templates/user/comment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'user.comment.new.title' | trans }}{% endblock %}

{% block body %}
    <h1>{{ 'user.comment.new.create.new.comment' | trans }}</h1>

    {{ include('comment/_form.html.twig') }}

    <a href="{{ path('comment_index') }}">{{ 'user.comment.new.back.to.list' | trans }}</a>
{% endblock %}

templates/user/comment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comment{% endblock %}

{% block body %}
    <h1>Comment</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ comment.id }}</td>
            </tr>
            <tr>
                <th>Text</th>
                <td>{{ comment.text }}</td>
            </tr>
            <tr>
                <th>Create_at</th>
                <td>{{ comment.createAt ? comment.createAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Update_at</th>
                <td>{{ comment.updateAt ? comment.updateAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Is_published</th>
                <td>{{ comment.isPublished ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('comment_index') }}">back to list</a>

    <a href="{{ path('comment_edit', {'id': comment.id}) }}">edit</a>

    {{ include('comment/_delete_form.html.twig') }}
{% endblock %}